secompufscar2015/urls.py
# coding: utf-8

from django.conf.urls import url
from secompufscar2018 import views

app_name = 'secompufscar2015'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # url(r'^apresentacao/$', views.apresentacao, name='apresentacao'),
    # url(r'^programacao/$', views.programacao, name='programacao'),
    # url(r'^cronograma/$', views.cronograma, name='cronograma'),
    # url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'),
    # url(r'^equipe/$', views.equipe, name='equipe'),
    # url(r'^contato/$', views.contato, name='contato'),
]

secompufscar2018/urls.py
import locale

from django.conf.urls import include
from django.urls import path

from secompufscar2018 import views

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
app_name = 'secompufscar2018'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq', views.faq, name='faq'),
    path('caravanas', views.caravanas, name='caravanas'),
    path('patrocinio', views.patrocinio, name='patrocinio'),
    path('equipe', views.equipe, name='equipe'),
    path('a-secomp/', views.a_secomp, name='asecomp'),
    path('a-secomp/apresentacao/', views.apresentacao, name='apresentacao'),
    path('a-secomp/sociocultural/', views.sociocultural, name='sociocultural'),
    path('recaptcha/', views.erro_recaptcha, name='recaptcha'),
    path('area-conteudo/',include('secompufscar2018.urls_area_conteudo')),
    path('api/',include('secompufscar2018.urls_apis')),
    path('processo-seletivo',views.processo_seletivo,name='processo-seletivo'),
    path('contato/enviar-email/', views.enviar_email_contato, name='enviar_email_contato'),
    path('caravanas/enviar-email/', views.enviar_email_caravana, name='enviar_email_caravana'),
    path('programacao/', views.programacao, name='programacao'),
    path('programacao/capture-the-flag/', views.capture_the_flag, name='ctf'),
    path('programacao/ministrantes/', views.ministrantes, name='ministrantes'),
    path('programacao/palestras/', views.palestras, name='palestras'),
    path('programacao/palestras-empresariais/', views.palestras_empresariais, name='palestras_empresariais'),
    path('programacao/minicursos/', views.minicursos, name='minicursos'),
    path('programacao/workshops/', views.workshops, name='workshops'),
    path('programacao/mesas-redondas/', views.mesas_redondas, name='mesasredondas'),
    path('programacao/cronograma/', views.cronograma, name='cronograma'),
    path('404/', views.erro_404, name='404'),
    path('500/', views.erro_500, name='400')
]

secompufscar_django/urls.py
from django.conf import settings
from django.conf.urls import include , handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

app_name = "secompufscar_django"


urlpatterns = [
    path('robots.txt', include('robots.urls')),
    path('admin/', admin.site.urls),
    path('2018/', include('secompufscar2018.urls', namespace='secompufscar2018')),
    path('2018/', include('secompufscar2017.urls', namespace='secompufscar2017')),
    path('2016/', include('secompufscar2016.urls', namespace='secompufscar2016')),
    path('2015/', include('secompufscar2015.urls', namespace='secompufscar2015')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', include('secompufscar2019.urls', namespace='root')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#handler404 = 'secompufscar2018.views.erro_404'
handler500 = 'secompufscar2018.views.erro_500'

secompufscar2018/models.py
import datetime
import os

from django.db import models
from secompufscar2018.secrets import token_urlsafe
from secompufscar_bd.models import Camiseta, Inscricao, Atividade

# Create your models here.

# Não foi possível importar a classe Diretoria, pois possui também os valores Voluntários/Coordenação Geral
DIRETORIAS =(
    ('SC','Sociocultural'),
    ('DM','Design e Marketing'),
    ('TI','Tecnologia de Informação'),
    ('JF','Jurídico-Financeira'),
    ('PA','Patrocínio'),
    ('CO','Conteúdo')
)
CURSOS =(
    ('BCC','Bacharelado em Ciência da Computação'),
    ('ENC','Eng. de Computação'),
    ('PPG','Pós Graduação'),
)
LOCOMOCAO = (
    ('Próprio', 'CARRO PRÓPRIO (COMBUSTÍVEL + PEDÁGIOS, CALCULADOS PELO JURÍDICO E FINANCEIRO)'),
    ('Ônibus', 'PASSAGEM DE ÔNIBUS (IDA E VOLTA)'),
    ('Alugado', 'CARRO ALUGADO (APENAS O VALOR DO ALUGUEL DO CARRO)')
)
LOCOMOCAO_MADDOG = (
    ('Fuel', 'Car fuel'),
    ('Bus', 'Bus ticket'),
    ('Other', 'Other')
)
CAMISETA_MADDOG = (
    ('PP', 'XS'),
    ('P','S'),
    ('M','M'),
    ('G','L'),
    ('GG','XL')
)



def picfolder():
    return 'images/secompufscar'+str(datetime.datetime.now().year)+'/ministrantes'


def path_and_rename(instance,filename):
    upload_to = picfolder()
    ext = filename.split('.')[-1]
    filename = token_urlsafe(8)+'.{}'.format(ext)
    return os.path.join(upload_to, filename)


class ConteudoInformacoesComuns(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField('Nome completo', max_length=50, blank=False, default="")
    email = models.EmailField('Email', blank=False, default="")
    tel = models.CharField('Telefone', max_length=15, blank=False, unique=True, default="")
    profissao = models.CharField('Profissão', max_length=100, blank=False, default="")
    empresa = models.CharField('Empresa', max_length=100, blank=False, default="")
    bio = models.TextField('Breve biografia', blank=True, default="")
    foto = models.FileField('Foto', upload_to=path_and_rename, blank=True)
    github = models.URLField('Github', max_length=255, blank=True)
    face = models.URLField('Facebook', max_length=255, blank=True)
    twitter = models.URLField('Twitter', max_length=255, blank=True)
    linkedin = models.URLField('LinkedIn', max_length=255, blank=True)
    tamanho_camiseta = models.ForeignKey(Camiseta,on_delete=models.CASCADE)
    cidade = models.CharField('Cidade', max_length=30, blank=False, default="")
    locomocao = models.BooleanField('Precisa de locomoção até a SECOMP?', blank=False, default=False)
    locomocao_tipo = models.CharField('Qual o tipo de locomoção?', blank=True, choices=LOCOMOCAO, max_length=10)
    data_chegada = models.DateField('Data de chegada em São Carlos', blank=False)
    data_saida = models.DateField('Data de saída de São Carlos', blank=False)
    acomodacao = models.BooleanField('Necessidade de acomodação (estadia em hotel)?', blank=False, default=False)
    vaga_acomodacao = models.BooleanField('Caso seja necessário uma estadia em hotel, é necessário1 uma vaga na garagem?', blank=True, default=False)
    obs = models.TextField('Observações', blank=True, default="")
    valido = models.BooleanField(default=False)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)


    class Meta:
        abstract = True


class ConteudoMesaRedonda(ConteudoInformacoesComuns):
    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Mesas Redonda')
        verbose_name_plural = (u'Mesas Redondas')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

class ConteudoMiniCurso(ConteudoInformacoesComuns):
    curso_titulo = models.CharField('Título do minicurso',max_length=80,blank=False,unique=True)
    curso_descricao = models.TextField('Descrição do minicurso')
    tipo_dinamica = models.TextField('Como se daria a dinâmica de participantes?')
    prereqs = models.TextField('Pré-requisitos:',blank=True)
    lab_hw = models.TextField('Recursos Hardware:',blank=False)
    lab_sw = models.TextField('Recursos Software:',blank=False)
    obs_lab = models.TextField('Observações:',blank=True)
    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Mini Curso')
        verbose_name_plural = (u'Mini Cursos')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

class ConteudoPalestra(ConteudoInformacoesComuns):
    palestra_titulo = models.CharField('Título da palestra',blank=False,max_length=255,unique=True)
    palestra_descricao = models.TextField('Descrição da palestra')
    recursos = models.TextField('Recursos:',blank=False)
    obs_palestra = models.TextField('Observações:', blank=True)
    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Palestra')
        verbose_name_plural = (u'Palestras')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

class MadDog(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField('Nome completo', max_length=50, blank=False, default="")
    email = models.EmailField('Email', blank=False, default="")
    tel = models.CharField('Telefone', max_length=15, blank=False, unique=True, default="")
    profissao = models.CharField('Profissão', max_length=100, blank=False, default="")
    empresa = models.CharField('Empresa', max_length=100, blank=False, default="")
    bio = models.TextField('Breve biografia', blank=True, default="")
    foto = models.FileField('Foto', upload_to=path_and_rename, blank=True)
    github = models.URLField('Github', max_length=255, blank=True)
    face = models.URLField('Facebook', max_length=255, blank=True)
    twitter = models.URLField('Twitter', max_length=255, blank=True)
    linkedin = models.URLField('LinkedIn', max_length=255, blank=True)
    tamanho_camiseta = models.CharField('Tamanho camiseta', choices=CAMISETA_MADDOG, blank=True, max_length=10)
    cidade = models.CharField('Cidade', max_length=30, blank=False, default="")
    locomocao = models.BooleanField('Will SECOMP UFSCar be in charge of your travel expenses?', blank=False, default=False)
    locomocao_tipo = models.CharField('Qual o tipo de locomoção?', blank=True, choices=LOCOMOCAO_MADDOG, max_length=10)
    data_chegada = models.DateField('Data de chegada em São Carlos', blank=False)
    data_saida = models.DateField('Data de saída de São Carlos', blank=False)
    acomodacao = models.BooleanField('Necessidade de acomodação (estadia em hotel)?', blank=False, default=False)
    vaga_acomodacao = models.BooleanField(
        'Caso seja necessário uma estadia em hotel, é necessário1 uma vaga na garagem?', blank=True, default=False)
    obs = models.TextField('Observações', blank=True, default="")
    valido = models.BooleanField(default=False)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)
    palestra_titulo = models.CharField('Título da palestra', blank=False, max_length=255, unique=True)
    palestra_descricao = models.TextField('Descrição da palestra')
    recursos = models.TextField('Recursos:', blank=False)
    obs_palestra = models.TextField('Observações:', blank=True)

    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'MadDog')
        verbose_name_plural = (u'MadDogs')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome


class ProcessoSeletivo(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, blank=False, default="")
    email = models.EmailField(max_length=100, blank=False, default="",unique=True)
    tel = models.CharField(max_length=20, blank=False, unique=True, default="")
    aprovado = models.BooleanField(default=False)
    primeira_opcao = models.CharField(blank=False, choices=DIRETORIAS, max_length=2)
    segunda_opcao = models.CharField(blank=False, choices=DIRETORIAS, max_length=2 )
    curso = models.CharField(max_length=3,choices=CURSOS, blank=False)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)

    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Processo Seletivo')
        verbose_name_plural = (u'Processo Seletivo')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

secompufscar2018/templates/secompufscar2018/contato.html
{% extends 'secompufscar2018/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Contato{% endblock %}

{% block meta_description %}Contribua para a SECOMP IX com um conteúdo.{% endblock meta_description %}

{% block body_content %}
    <style>

    </style>
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered stackable grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Contato
                </h1>
            </div>

            <div class="ui wide computer sixteen wide tablet sixteen wide mobile column wow fadeInUp" data-wow-delay="0.3s" id="forms">
                <h2 class="ui centered menor_padding_top header" id="entre_em_contato_header">
                    É uma empresa multinacional? É dono de uma empresa? É um aluno? É alguém que tenha algo a contribuir com a SECOMP IX?
                    Entre em contato conosco =)
                </h2>
                <br><br>
                <div class="ui grid container centered">
                    <div class="stackable row">
                        <a class="ui red button four wide column" id="botao_minicurso" href="{% url 'secompufscar2018:mini_curso' %}">
                            <div style="text-align: center;"><p>Quero dar um minicurso!</p></div>
                            <br>
                            <div style="text-align: center;"><i class="ui huge white terminal icon"></i></div>
                        </a>

                        <a class="ui blue button four wide column" id="botao_mesa" href="{% url 'secompufscar2018:mesa_redonda' %}">
                            <div style="text-align: center;"><p>Quero ministrar a mesa redonda!</p></div>
                            <br>
                            <div style="text-align: center;"><i class="ui huge white comments icon"></i></div>
                        </a>

                        <a class="ui green button four wide column" href="{% url 'secompufscar2018:palestra' %}" id="botao_palestra">
                            <div style="text-align: center;"><p>Quero ministrar uma palestra!</p></div>
                            <br>
                            <div style="text-align: center;"><i class="ui huge white microphone icon"></i></div>
                        </a>
                    </div>
                </div>
                <br><br>
            </div>

        </div>
    </div>

    <script type="text/javascript">

        $('#botao_minicurso').on('click',function () {
            $('#botao_minicurso').addClass('loading');
        });

        $('#botao_palestra').on('click',function () {
            $('#botao_palestra').addClass('loading');
        });

        $('#botao_mesa').on('click',function () {
            $('#botao_mesa').addClass('loading');
        });

    </script>

    {% include 'secompufscar2018/helpers/patrocinadores.html' %}
{% endblock body_content %}

secompufscar2018/templates/secompufscar2018/faq.html
{% extends 'secompufscar2018/helpers/base.html' %}

{% load staticfiles %}

{% block title %}SECOMP UFSCar - FAQ{% endblock %}

{% block meta_description %}Tire suas dúvidas em nosso FAQ ou entre em contato conosco.{% endblock meta_description %}

{% block body_content %}
    <script src='https://www.google.com/recaptcha/api.js?hl=pt-BR'></script>
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered stackable grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    FAQ
                </h1>
            </div>
            {% if perguntas_frequentes %}
                <div class="ui nine wide computer sixteen wide tablet sixteen wide mobile column">
                    <div class="ui accordion wow fadeInUp" id="accordion_perguntas_frequentes" data-wow-delay="0.3s">
                        {% for pergunta_frequente in perguntas_frequentes %}
                            <div class="{% if forloop.counter == 1 %}active {% endif %}title">
                                <i class="dropdown icon"></i>
                                {{ pergunta_frequente.pergunta|safe }}
                            </div>
                            <div class="{% if forloop.counter == 1 %}active {% endif %}content">
                                {{ pergunta_frequente.resposta|safe }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="ui one wide computer tablet only column"></div>
            {% endif %}

            <div class="ui six wide computer sixteen wide tablet sixteen wide mobile column wow fadeInUp"
                 data-wow-delay="0.3s">
                <h2 class="ui centered menor_padding_top header" id="entre_em_contato_header">
                    Tem alguma dúvida sobre o evento? Entre em contato com a organização
                </h2>
                <form class="ui form" novalidate>
                    {% csrf_token %}
                    <div class="field">
                        <label for="id_nome">Seu nome:</label>
                        {{ form.nome }}
                    </div>
                    <div class="field">
                        <label for="id_email">Seu e-mail:</label>
                        {{ form.email }}
                    </div>
                    <div class="field">
                        <label for="id_mensagem">Mensagem:</label>
                        {{ form.mensagem }}
                    </div>
                    <div class="field">
                        <div class="g-recaptcha" data-sitekey="6LerM0gUAAAAAAc52ET2parkXXBNm1YvHYOHZ2KP"
                             data-callback="captcha_filled"
                             data-expired-callback="captcha_expired"></div>
                    </div>
                    <div class="ui black button" id="botao_enviar_email">
                        <i class="send icon"></i>
                        Enviar mensagem
                    </div>
                    <div class="ui icon success message">
                        <i class="send icon"></i>
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">Sua mensagem foi enviada com sucesso!</div>
                            <p>Entraremos em contato em breve :-)</p>
                        </div>
                    </div>
                    <div class="ui icon error message">
                        <i class="frown icon"></i>
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">Houve um erro no envio de sua mensagem!</div>
                            <p>Desculpe-nos pelo transtorno.</p>
                            <p>Por favor, entre em contato conosco pelo e-mail <a
                                    href="mailto:ti@secompufscar.com.br">
                                ti@secompufscar.com.br</a> e informe também que obteve erro ao enviar a mensagem
                                pelo site.
                            </p>
                        </div>
                    </div>
                    <div class="ui icon warning message" id="captcha_warning">
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">Preencha o captcha!</div>
                            <p> Confio que você não é um robô! Mas o nosso servidor infelizmente não. :/
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="{% static 'secompufscar2018/js/formulario_faq.js' %}"></script>
    {% include 'secompufscar2018/helpers/patrocinadores.html' %}
{% endblock body_content %}

secompufscar2018/templates/secompufscar2018/patrocinio.html
{% extends 'secompufscar2018/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Patrocínio{% endblock %}

{% block meta_description %}Conheça os patrocinadores da IX SECOMP UFSCar.{% endblock meta_description %}

{% block body_content %}
    <!--<div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered stackable grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Seja um patrocinador
                </h1>
                <div class="ui segment big inverted wow fadeInUp sixteen">
                    <div style="text-align: center;"><b>Entre e contato com a organização enviando um email para: <a href="mailto:contato@secompufscar.com.br"><i class="big mail inverted square grey icon"></i>contato@secompufscar.com.br</b><br></div>
                </div>

            </div>
        </div>
    </div>-->
    {% include 'secompufscar2018/helpers/patrocinadores.html' %}
{% endblock body_content %}

secompufscar2018/templates/secompufscar2018/processo_seletivo.html
{% extends 'secompufscar2018/helpers/base.html' %}

{% load staticfiles %}

{% block title %}SECOMP UFSCar - Processo Seletivo{% endblock %}

{% block meta_description %}Venha fazer parte do processo seletivo.{% endblock meta_description %}

{% block body_content %}
    <script src='https://www.google.com/recaptcha/api.js?hl=pt-BR'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered stackable grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Faça parte da equipe!
                </h1>
            </div>
            <div class="ui nine wide computer sixteen wide tablet sixteen wide mobile column">
                <div>
                    <h2 class="ui centered menor_padding_top header wow fadeInUp" data-wow-delay="0.3s">Sobre as diretorias</h2>
                    <div class="ui accordion wow fadeInUp" data-wow-delay="0.3s">
                        <div class="title active">
                            <i class="dropdown icon"></i>
                            <b>Design & Marketing (DM)</b>
                        </div>
                        <div class="content active">
                            <p class="transition">A diretoria de Design & Marketing tem a função de
                                fazer a manutenção e divulgação da imagem da SECOMP pelas redes sociais
                                (Facebook, Twitter e Instagram), além de ser responsável pela criação de
                                materiais gráficos para a mesma, estes sendo banners, panfletos, toda a arte
                                do kit, entre outros. Para que isso seja realizado, são usadas ferramentas
                                de edição como Photoshop e Corel.</p>
                        </div>

                        <div class="title">
                            <i class="dropdown icon"></i>
                            <b>Sociocultural</b>
                        </div>
                        <div class="content">
                            <p class="transition">A diretoria Sociocultural da SECOMP tem o objetivo de promover
                                o espírito de solidariedade entre os participantes da Semana com instituições
                                da cidade, além de promover eventos culturais e de integração, como a SECOMP
                                XP e o Churrasco de Integração da SECOMP.</p>
                        </div>

                        <div class="title">
                            <i class="dropdown icon"></i>
                            <b>Tecnologia da Informação (TI)</b>
                        </div>

                        <div class="content">
                            <p class="transition">A diretoria de TI é responsável por criar e
                                gerenciar todos os sistemas e aplicações que dão suporte ao funcionamento
                                da SECOMP, como o sistema de cadastro no evento, aplicativo de controle
                                de presença, site e o aplicativo Android.</p>
                        </div>

                        <div class="title">
                            <i class="dropdown icon"></i>
                            <b>Jurídico-Financeira</b>
                        </div>

                        <div class="content">
                            <p class="transition">A diretoria Jurídico-Financeira da SECOMP é responsável
                                por todo o planejamento financeiro, pelo controle do fluxo de caixa
                                e pela organização dos documentos, contratos e orçamentos relacionados à SECOMP.</p>
                        </div>

                        <div class="title">
                            <i class="dropdown icon"></i>
                            <b>Patrocínio</b>
                        </div>

                        <div class="content">
                            <p class="transition">A diretoria de Patrocínio é encarregada de fazer a arrecadação de verba
                                proveniente das empresas parceiras da SECOMP, e a manutenção de contato com
                                elas. A diretoria elabora estratégias para que a parceria traga o máximo de
                                benefícios possíveis, entre a SECOMP e as empresas que apoiam o projeto, desde
                                empreendimentos locais até grandes multinacionais.</p>
                        </div>

                        <div class="title">
                            <i class="dropdown icon"></i>
                            <b>Conteúdo</b>
                        </div>

                        <div class="content">
                            <p class="transition">A diretoria de Conteúdo tem como objetivo organizar o cronograma da SECOMP
                                e trazer as mais diversas áreas da Computação para o evento em forma de palestras,
                                minicursos, workshops, mesas redondas, entre outros. Durante o ano, os membros da
                                diretoria contatam empresas, professores, pesquisadores e ex-alunos de computação,
                                para que a Semana tenha a maior qualidade possível para os participantes.</p>
                        </div>
                        <div class="ui divider"></div>
                        <a href="{% static 'secompufscar2018/pdfs/editalv2.pdf' %}" class="ui green button">Acesse o novo edital aqui</a>
                    </div>
                </div>
            </div>
            <div class="ui one wide computer tablet only column"></div>
            <div class="ui six wide computer sixteen wide tablet sixteen wide mobile column">
                <h2 class="ui centered menor_padding_top header wow fadeInUp" data-wow-delay="0.3s">Inscreva-se</h2>
                <form class="ui form wow fadeInUp" data-wow-delay="0.3s" method="POST" id="post-form" action="{%url 'secompufscar2018:cadastra_processo_seletivo'%}">
                    {% csrf_token %}
                    <div class="ui sixteen wide required field">
                        <label>Nome completo:</label>
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            {{ form.nome }}
                        </div>
                    </div>
                    <div class="ui sixteen wide required field">
                        <label>Telefone:</label>
                        <div class="ui left icon input">
                            <i class="call icon"></i>
                            {{ form.tel }}
                        </div>
                    </div>
                    <div class="ui sixteen wide required field">
                        <label>Email:</label>
                        <div class="ui left icon input">
                            <i class="envelope icon"></i>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="ui sixteen wide required field">
                        <label>Primeira opção de diretoria:</label>
                        {{ form.primeira_opcao }}
                    </div>
                    <div class="ui sixteen wide required field">
                        <label>Segunda opção de diretoria:</label>
                        {{ form.segunda_opcao }}
                    </div>
                    <div class="ui sixteen wide required field">
                        <label>Curso:</label>
                        {{ form.curso }}
                    </div>
                    <div class="field">
                        <div class="g-recaptcha" data-sitekey="6LerM0gUAAAAAAc52ET2parkXXBNm1YvHYOHZ2KP" data-callback="captcha_filled"
                             data-expired-callback="captcha_expired"></div>
                    </div>
                    <button class="ui submit button" type="submit" id="botao_enviar"><i class="send icon"></i>Inscrever!</button>
                </form>
                <div class="ui icon success message" id="sucesso">
                    <i class="send icon"></i>
                    <i class="close icon"></i>
                    <div class="content">
                        <div class="header">Sua inscrição foi enviada com sucesso!</div>
                        <p>Entraremos em contato em breve :-)</p>
                        <p><a class="ui positive button" href="{% url 'secompufscar2018:index' %}">Voltar</a></p>
                    </div>
                </div>
                <div class="ui icon error message" id="erro">
                    <i class="frown icon"></i>
                    <i class="close icon"></i>
                    <div class="content">
                        <div class="header">Houve um erro no envio de seu contato!</div>
                        <div id="msgs"></div>
                        <p>Se você acha que não deveria estar vedo isso por favor, entre em contato conosco pelo e-mail <a
                                href="mailto:ti@secompufscar.com.br">
                            ti@secompufscar.com.br</a> e informe o ocorrido
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'secompufscar2018/js/formulario_ps.js' %}"></script>

{% endblock body_content %}