secompufscar2015/urls.py
# coding: utf-8

from django.conf.urls import url
from secompufscar2018 import views

app_name = 'secompufscar2015'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # url(r'^apresentacao/$', views.apresentacao, name='apresentacao'),
    # url(r'^programacao/$', views.programacao, name='programacao'),
    # url(r'^cronograma/$', views.cronograma, name='cronograma'),
    # url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'),
    # url(r'^equipe/$', views.equipe, name='equipe'),
    # url(r'^contato/$', views.contato, name='contato'),
]

secompufscar2017/urls.py
# coding: utf-8

from django.conf.urls import include, url
from secompufscar2017 import views

app_name = 'secompufscar2017'
urlpatterns = [
    url(r'^area-do-participante/', include('secompufscar2017.urls_area_do_participante')),
    url(r'^area-administrativa/', include('secompufscar2017.urls_area_administrativa')),
    url(r'^api/', include('secompufscar2017.urls_apis')),
]

secompufscar2018/urls.py
import locale

from django.conf.urls import include
from django.urls import path

from secompufscar2018 import views

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
app_name = 'secompufscar2018'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq', views.faq, name='faq'),
    path('caravanas', views.caravanas, name='caravanas'),
    path('patrocinio', views.patrocinio, name='patrocinio'),
    path('equipe', views.equipe, name='equipe'),
    path('a-secomp/', views.a_secomp, name='asecomp'),
    path('a-secomp/apresentacao/', views.apresentacao, name='apresentacao'),
    path('a-secomp/sociocultural/', views.sociocultural, name='sociocultural'),
    path('recaptcha/', views.erro_recaptcha, name='recaptcha'),
    path('area-conteudo/',include('secompufscar2018.urls_area_conteudo')),
    path('api/',include('secompufscar2018.urls_apis')),
    path('processo-seletivo',views.processo_seletivo,name='processo-seletivo'),
    path('contato/enviar-email/', views.enviar_email_contato, name='enviar_email_contato'),
    path('caravanas/enviar-email/', views.enviar_email_caravana, name='enviar_email_caravana'),
    path('programacao/', views.programacao, name='programacao'),
    path('programacao/capture-the-flag/', views.capture_the_flag, name='ctf'),
    path('programacao/ministrantes/', views.ministrantes, name='ministrantes'),
    path('programacao/palestras/', views.palestras, name='palestras'),
    path('programacao/palestras-empresariais/', views.palestras_empresariais, name='palestras_empresariais'),
    path('programacao/minicursos/', views.minicursos, name='minicursos'),
    path('programacao/workshops/', views.workshops, name='workshops'),
    path('programacao/mesas-redondas/', views.mesas_redondas, name='mesasredondas'),
    path('programacao/cronograma/', views.cronograma, name='cronograma'),
    path('404/', views.erro_404, name='404'),
    path('500/', views.erro_500, name='400')
]

secompufscar_django/urls.py
from django.conf import settings
from django.conf.urls import include , handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

app_name = "secompufscar_django"


urlpatterns = [
    path('robots.txt', include('robots.urls')),
    path('admin/', admin.site.urls),
    path('2018/', include('secompufscar2018.urls', namespace='secompufscar2018')),
    path('2018/', include('secompufscar2017.urls', namespace='secompufscar2017')),
    path('2016/', include('secompufscar2016.urls', namespace='secompufscar2016')),
    path('2015/', include('secompufscar2015.urls', namespace='secompufscar2015')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', include('secompufscar2019.urls', namespace='root')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#handler404 = 'secompufscar2018.views.erro_404'
handler500 = 'secompufscar2018.views.erro_500'

secompufscar2017/models.py
from django.db import models


class CaraterProjeto(models.Model):
    carater = models.CharField(verbose_name="Caráter de projeto", max_length=15, unique=True)

    def __str__(self):
        return str(self.carater)


class Projeto(models.Model):
    # Atributos da tabela projeto
    nome = models.CharField(verbose_name="Nome do projeto", max_length=100)
    areas = models.CharField(verbose_name="Áreas abordadas", max_length=200)
    carater = models.ManyToManyField(CaraterProjeto, verbose_name='Carater do projeto')
    conteudo = models.TextField(verbose_name="Conteúdo abordado")
    descricao = models.TextField(verbose_name="Descrição do projeto")
    link_video = models.CharField(verbose_name="Link para vídeo", max_length=100, null=True, blank=True)
    relacao_computacao = models.TextField(verbose_name="Relação com a computação")
    material_utilizado = models.TextField(verbose_name="Material utilizado", blank=True)
    objetivo = models.TextField(verbose_name="Objetivo do projeto", max_length=2000)
    resultados = models.TextField(verbose_name="Resultados já alcançados")
    # Responsavel pelo projeto: os seguintes campos estão inclusos na tabela projeto
    # e não integrante pois são relativos ao único responsável pelo projeto.
    responsavel = models.ForeignKey('IntegranteProjeto', on_delete=models.CASCADE, null=True)
    facebook_responsavel = models.CharField(verbose_name="Facebook do responsável", max_length=100, null=True,
                                            blank=True)
    email_responsavel = models.EmailField(verbose_name="Email do responsável")
    telefone_responsavel = models.CharField(verbose_name="Telefone do responsavel", max_length=15)

    aprovado = models.NullBooleanField(verbose_name="Status de aprovação", null=True)

    def __str__(self):
        return 'Projeto: ' + str(self.nome)

    class Meta:
        verbose_name = 'projeto'
        verbose_name_plural = 'projetos'


class IntegranteProjeto(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=100)
    projeto_participante = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nome) + '[projeto: ' + self.projeto_participante.nome + ']'

    class Meta:
        verbose_name = 'integrante'
        verbose_name_plural = 'integrantes'

secompufscar2017/views.py
# coding=utf-8
import requests
from django.db.models import Min
from django.db.models.signals import post_save, post_delete, m2m_changed
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import render

from secompufscar2017.forms import FormularioDeContato, FormularioDeCadastroDeProjetos
from secompufscar2017.models import Projeto, CaraterProjeto, IntegranteProjeto
from secompufscar2017.utilities import *
from secompufscar_bd.models import *

evento = get_evento_atual()


def _ajustar_tamanho_de_nome_para_pagina_equipe(membros):
    for membro in membros:
        sobrenome_completo = membro.participante.usuario.last_name
        membro.participante.usuario.last_name = abreviar_sobrenome(sobrenome_completo=sobrenome_completo, min_len=20)
    return membros


def _get_diretorias():
    return [{'nome': diretoria.nome,
             'membros': _ajustar_tamanho_de_nome_para_pagina_equipe(evento.membros_equipe.filter(
                 diretoria=diretoria).order_by('-cargo__nome', 'participante__usuario__first_name',
                                               'participante__usuario__last_name'))}
            for diretoria in Diretoria.objects.all()]


def _get_perguntas_frequentes():
    return evento.perguntas_frequentes.order_by('prioridade')


def _get_patrocinadores_por_cota(nome_cota):
    return evento.patrocinadores.filter(ativo_site=True, cota__nome=nome_cota).order_by('ordem_site')


def _get_tipo_atividade(nome_tipo_atividade):
    try:
        return TipoAtividade.objects.get(nome=nome_tipo_atividade)
    except ObjectDoesNotExist:
        return None


def _get_atividades_por_tipo(nome_tipo_atividade):
    return evento.atividades.filter(ativa=True, tipo=_get_tipo_atividade(nome_tipo_atividade=nome_tipo_atividade)). \
        annotate(primeira_data=Min('horarios__data_hora_inicio')).order_by('primeira_data', 'titulo')


def _get_menus_site_ativos():
    return [menu.nome for menu in get_evento_atual().menus_site_ativos.filter(ativo=True)]


def _get_data_hora_inicio_evento():
    return evento.data_hora_inicio_evento


def _get_datas_inscricoes_por_atividade(tipo_atividade):
    try:
        tipo_atividade = evento.datas_inscricoes_atividades.get(tipo_atividade=tipo_atividade)
        return {
            "inicio": tipo_atividade.data_hora_inicio_inscricoes,
            "fim": tipo_atividade.data_hora_fim_inscricoes
        }
    except ObjectDoesNotExist:
        return {}


def _get_datas_inscricoes_desafio_programadores():
    if evento.desafio_programadores is not None:
        return {
            "inicio": evento.desafio_programadores.inicio_inscricoes_desafio_programadores,
            "fim": evento.desafio_programadores.fim_inscricoes_desafio_programadores
        }
    return {}


def _get_datas_inscricoes_atividades():
    return {
        MINICURSOS: _get_datas_inscricoes_por_atividade(tipo_atividade=_get_tipo_atividade('Minicurso')),
        WORKSHOPS: _get_datas_inscricoes_por_atividade(tipo_atividade=_get_tipo_atividade('Workshop')),
        PROCESSOS_SELETIVOS:
            _get_datas_inscricoes_por_atividade(tipo_atividade=_get_tipo_atividade('Processo Seletivo')),
        DESAFIO_PROGRAMADORES: _get_datas_inscricoes_desafio_programadores()
    }


def _get_tipos_atividades_com_cronograma_fechado():
    return [tipo.tipo_atividade.nome for tipo in evento.tipos_atividades.filter(cronograma_fechado=True)]


def _get_ministrantes():
    return Ministrante.objects.filter(atividade__evento=get_evento_atual()).order_by('nome')


def _get_atividades():
    atividades = {}
    for tipo_atividade in TipoAtividade.objects.all():
        atividades[converter_para_lowercase_e_sem_espacos(tipo_atividade.nome)] = get_evento_atual().atividades.filter(
            tipo=_get_tipo_atividade(nome_tipo_atividade=tipo_atividade.nome), ativa=True).order_by('titulo')
    return atividades


def _get_data_ultima_atualizacao_atividades():
    atividades = get_evento_atual().atividades.filter(ativa=True).order_by('-ultima_atualizacao_em')
    try:
        return atividades[0].ultima_atualizacao_em
    except Exception:
        return None


@receiver(post_save, sender=Atividade)
@receiver(post_delete, sender=Atividade)
def atualizar_data_ultima_atualizacao_atividades(sender, **kwargs):
    dicionario_contexto[DATA_ULTIMA_ATUALIZACAO_ATIVIDADES] = _get_data_ultima_atualizacao_atividades()


def _get_data_ultima_atualizacao_ministrantes():
    ministrantes = Ministrante.objects.filter(atividade__evento=get_evento_atual()).order_by('-ultima_atualizacao_em')
    try:
        return ministrantes[0].ultima_atualizacao_em
    except Exception:
        return None


@receiver(post_save, sender=Ministrante)
@receiver(post_delete, sender=Ministrante)
def atualizar_data_ultima_atualizacao_ministrantes(sender, **kwargs):
    dicionario_contexto[DATA_ULTIMA_ATUALIZACAO_MINISTRANTES] = _get_data_ultima_atualizacao_ministrantes()


def _get_data_ultima_atualizacao_patrocinadores():
    patrocinadores = evento.patrocinadores.filter(ativo_site=True).order_by('-ultima_atualizacao_em')
    try:
        return patrocinadores[0].ultima_atualizacao_em
    except Exception:
        return None


@receiver(post_save, sender=Patrocinador)
@receiver(post_delete, sender=Patrocinador)
def atualizar_data_ultima_atualizacao_patrocinadores(sender, **kwargs):
    dicionario_contexto[DATA_ULTIMA_ATUALIZACAO_PATROCINADORES] = _get_data_ultima_atualizacao_patrocinadores()


def _get_dicionario_contexto():
    return {
        'producao': is_sistema_em_producao(),
        'google_analytics_key': get_google_analytics_key(),
        PATROCINADORES: {
            converter_para_lowercase_e_sem_espacos(COTA_DIAMANTE):
                _get_patrocinadores_por_cota(nome_cota=COTA_DIAMANTE),
            converter_para_lowercase_e_sem_espacos(COTA_OURO):
                _get_patrocinadores_por_cota(nome_cota=COTA_OURO),
            converter_para_lowercase_e_sem_espacos(COTA_PRATA):
                _get_patrocinadores_por_cota(nome_cota=COTA_PRATA),
            converter_para_lowercase_e_sem_espacos(COTA_DESAFIO_PROGRAMADORES):
                _get_patrocinadores_por_cota(nome_cota=COTA_DESAFIO_PROGRAMADORES),
            converter_para_lowercase_e_sem_espacos(COTA_APOIO):
                _get_patrocinadores_por_cota(nome_cota=COTA_APOIO),
        },
        'diretorias': _get_diretorias(),
        'perguntas_frequentes': _get_perguntas_frequentes(),
        PALESTRAS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PALESTRA),
        PALESTRAS_EMPRESARIAIS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PALESTRA_EMPRESARIAL),
        MINICURSOS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_MINICURSO),
        WORKSHOPS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_WORKSHOP),
        MESAS_REDONDAS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_MESA_REDONDA),
        PROCESSOS_SELETIVOS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PROCESSO_SELETIVO),
        'menus_ativos': _get_menus_site_ativos(),
        'data_hora_inicio_evento': _get_data_hora_inicio_evento(),
        'evento': get_evento_atual(),
        'data_hora_inscricoes_atividades': _get_datas_inscricoes_atividades(),
        'tipos_atividade_com_cronograma_fechado': _get_tipos_atividades_com_cronograma_fechado(),
        'ministrantes': _get_ministrantes(),
        'atividades': _get_atividades(),
        DATA_ULTIMA_ATUALIZACAO_ATIVIDADES: _get_data_ultima_atualizacao_atividades(),
        DATA_ULTIMA_ATUALIZACAO_MINISTRANTES: _get_data_ultima_atualizacao_ministrantes(),
        DATA_ULTIMA_ATUALIZACAO_PATROCINADORES: _get_data_ultima_atualizacao_patrocinadores(),
        'permissoes': {}
    }


dicionario_contexto = _get_dicionario_contexto()


def _atualizar_dicionario_contexto():
    dicionario_contexto.update(_get_dicionario_contexto())
    atualizar_dicionario_permissoes()


@receiver(post_save, sender=Evento)
@receiver(post_delete, sender=Evento)
def _atualizar_evento_dicionario_contexto(sender, **kwargs):
    _atualizar_dicionario_contexto()


m2m_changed.connect(_atualizar_evento_dicionario_contexto, sender=Evento.menus_site_ativos.through)
m2m_changed.connect(_atualizar_evento_dicionario_contexto, sender=Evento.tipos_atividades.through)


def atualizar_dicionario_permissoes():
    dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA'] = []
    for permissao in get_evento_atual().permissoes.all():
        dicionario_contexto['permissoes'][permissao.nome] = []
        for participante in permissao.usuarios_permitidos.all():
            dicionario_contexto['permissoes'][permissao.nome].append(participante.usuario)
            if participante.usuario not in dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA']:
                dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA'].append(participante.usuario)


def index(request):
    dicionario_contexto[AGORA] = timezone.now()
    return render(request=request, template_name=TEMPLATE_INDEX, context=dicionario_contexto)


def a_secomp(request):
    return render(request=request, template_name=TEMPLATE_A_SECOMP, context=dicionario_contexto)


def apresentacao(request):
    return render(request=request, template_name=TEMPLATE_APRESENTACAO, context=dicionario_contexto)


def historia(request):
    # TODO implementar página História
    return HttpResponseRedirect('/2017/')


def sociocultural(request):
    return render(request=request, template_name=TEMPLATE_SOCIOCULTURAL, context=dicionario_contexto)


def programacao(request):
    return render(request=request, template_name=TEMPLATE_PROGRAMACAO, context=dicionario_contexto)


def palestras(request):
    dicionario_contexto[AGORA] = timezone.now()
    dicionario_contexto[ATIVIDADES] = dicionario_contexto[PALESTRAS]
    return render(request=request, template_name=TEMPLATE_ATIVIDADES, context=dicionario_contexto)

secompufscar2017/templates/secompufscar2017/programacao/churrasco.html
{% extends 'secompufscar2017/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Churrasco{% endblock %}

{% block meta_description %}Faça login para entrar na Área do Participante da VII SECOMP
    UFSCar.{% endblock meta_description %}

{% block body_content %}

    <!-- Pacotes -->
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">CHURRASCO DE INTEGRAÇÃO</h1>
                <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.6s">Um churrasco descontraído
                    Quinta-feira, dia 29/09, a partir das 19h. Apenas R$ 25,00 para inscritos no pacote FULL ou R$
                    30,00 para os demais. Vagas limitadas. Preencha o formulário a seguir para receber mais
                    informações.</h3>
            </div>
            <div class="ui sixteen wide column wow fadeInUp">
                <p align="center">
                    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe8tCgwbtmOYo1mU6NQLQR1bj1SwEsvJf6sYJ2dz3GljXT0vQ/viewform?embedded=true"
                            width="760" height="1900" frameborder="0" marginheight="0" marginwidth="0">Carregando…
                    </iframe>
                </p>
            </div>
        </div>
    </div>

    {% include 'secompufscar2017/helpers/patrocinadores.html' %}

{% endblock body_content %}

secompufscar2017/templates/secompufscar2017/programacao/cronograma.html
{% extends 'secompufscar2017/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Cronograma{% endblock %}

{% block meta_description %}Acesse aqui o cronograma da IX SECOMP UFSCar.{% endblock meta_description %}

{% block body_content %}

    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">CRONOGRAMA</h1>
                <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.6s">Consulte aqui um resumo das
                    atividades da VIII SECOMP e seus respectivos locais.</h3>
            </div>
            <div class="ui sixteen wide center aligned column wow fadeInUp">
                <div class="ui huge image">
                    <img src="{% static 'secompufscar2017/images/cronograma/cronograma.png' %}"
                         alt="Cronograma da IX SECOMP UFSCar.">
                </div>
            </div>
        </div>
    </div>

    {% include 'secompufscar2017/helpers/patrocinadores.html' %}

{% endblock body_content %}

secompufscar2017/templates/secompufscar2017/programacao/enterprise_day.html
{% extends 'secompufscar2017/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Enterprise Day{% endblock %}

{% block meta_description %}Veja aqui as empresas que virão para a VIII SECOMP
    UFSCar.{% endblock meta_description %}

{% block body_content %}

    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Enterprise Day - Estandes
                </h1>
                <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.6s">Venha conhecer de perto algumas
                    das maiores empresas de tecnologia da região! Terça-feira, dia 19/09, à partir das 12h no
                    Saguão da Biblioteca Comunitária. As seguintes empresas terão estandes:
                </h3>

                <div class="ui grid centered">
                    {% for empresa in estandes %}
                        {% if empresa.cota.nome == 'Diamante' %}
                            <div class="ui six wide computer six wide tablet sixteen wide mobile center aligned column wow fadeInUp"
                                 data-wow-delay="0.6s">
                                <img class="ui fluid image" src="{{ empresa.logo.url }}">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="ui grid centered">
                    {% for empresa in estandes %}
                        {% if empresa.cota.nome != 'Diamante' %}
                            <div class="ui four wide computer four wide tablet ten wide mobile center aligned column wow fadeInUp"
                                 data-wow-delay="0.7s">
                                <img class="ui fluid image" src="{{ empresa.logo.url }}">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Palestras Empresariais
                </h1>

                <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.5s">
                    Veja um resumo das palestras empresariais que acontecerão no Entreprise Day. Para mais
                    detalhes, visite a página
                    <a href="{% url 'secompufscar2017:palestras_empresariais' %}">Palestras Empresariais</a>
                    do nosso site.
                </h3>
                <table class="ui celled striped table wow fadeInUp" data-wow-delay="0.7s">
                    <thead>
                        <tr>
                            <th>Palestra</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for atividade in atividades %}
                            <tr>
                                <td>
                                    <div class="ui internally celled grid">
                                        <h4 class="ui image header">
                                            {% for ministrante in atividade.ministrante.all %}
                                                {% if ministrante.foto %}
                                                    <img src="{{ ministrante.foto.url }}"
                                                         class="ui mini bordered rounded image">
                                                {% endif %}
                                            {% endfor %}

                                            <div class="content">
                                                {{ atividade.titulo }}
                                                {% if atividade.tipo.nome != 'Processo Seletivo' %}
                                                    <div class="sub header">
                                                        {% for ministrante in atividade.ministrante.all %}
                                                            {{ ministrante.nome }} {{ ministrante.sobrenome }}{% if not forloop.last %}, {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </h4>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="ui sixteen wide column">
                    <h4 class="ui centered header">Programação sujeita a alterações.</h4>
                </div>
            </div>
        </div>
    </div>

    {% include 'secompufscar2017/helpers/patrocinadores.html' %}
{% endblock body_content %}

secompufscar2017/templates/secompufscar2017/programacao/feira_de_projetos.html
{% extends 'secompufscar2017/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Feira de Projetos{% endblock %}

{% block meta_description %}
    Descrição e edital da Feira de Projetos da VIII SECOMP USFCar
{% endblock meta_description %}

{% block body_content %}
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered grid container">
            <div class="ui sixteen wide column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
                    Feira de Projetos</h1>
                {% if 'Projeto' not in atividades_cronograma_fechado %}
                    <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.6s">
                        Submissão de projetos finalizada. Em breve divulgaremos os projetos selecionados.
                    </h3>
                {% else %}
                    <h3 class="ui centered header wow fadeInUp" data-wow-delay="0.6s">
                        Confira os projetos submetidos e aprovados para apresentação na Feira de Projetos da SECOMP.
                    </h3>

                {% endif %}
            </div>

            {% if 'Projeto' not in atividades_cronograma_fechado %}
                {% include 'secompufscar2017/programacao/helpers/formulario_cadastro_projeto.html' %}
            {% else %}

                <div class="ui ten wide computer ten wide tablet sixteen wide mobile column">
                    <div class="ui two column stackable center aligned grid" id="detalhes_desafio_grid">
                        <div class="column wow fadeInUp" data-wow-delay="0.3s">
                            <h3 class="ui center aligned icon header">
                                <i class="calendar icon"></i>
                                QUANDO?</h3>
                            <b>Sexta-feira, 22/09, das 8h às 12h</b>
                        </div>

                        <div class="column wow fadeInUp" data-wow-delay="0.4s">
                            <h3 class="ui center aligned icon header">
                                <i class="marker icon"></i>
                                ONDE?</h3>
                            <b>Departamento de Computação</b>
                        </div>
                    </div>
                </div>

                {% for projeto in projetos_aprovados %}
                    <div class="ui sixteen wide column wow fadeInUp" data-wow-delay="0.2s">
                        <div class="ui top attached header">
                            <h1 class="ui header">{{ projeto.nome }}</h1>
                        </div>

                        <div class="ui attached fluid segment">

                            <h3 class="ui header">
                                {% for integrante in projeto.integranteprojeto_set.all %}
                                    {{ integrante.nome }}{% if not forloop.last %} - {% endif %}
                                {% endfor %}
                            </h3>
                            <p class="justificado">
                                {{ projeto.descricao }}
                            </p>
                            <p class="justificado">
                                <b>Relação com a computação:</b> {{ projeto.relacao_computacao }}
                            </p>
                            {% for carater_projeto in projeto.carater.all %}
                                <div class="ui label">
                                    {% if carater_projeto.carater == 'Pesquisa' %}
                                        <i class="university icon"></i>
                                    {% elif carater_projeto.carater == 'Extensão' %}
                                        <i class="world icon"></i>
                                    {% elif carater_projeto.carater == 'Ensino' %}
                                        <i class="student icon"></i>
                                    {% endif %}
                                    {{ carater_projeto.carater }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    {% include 'secompufscar2017/helpers/patrocinadores.html' %}

{% endblock body_content %}

secompufscar2017/templates/secompufscar2017/programacao/programacao.html
{% extends 'secompufscar2017/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Programação{% endblock %}

{% block meta_description %}A programação deste ano conta com palestras, minicursos, workshops, mesas-redondas, Game
    Night, Desafio de Programadores, Enterprise Day e muito mais!{% endblock meta_description %}

{% block body_content %}
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <div class="ui centered grid container">
            <div class="sixteen wide center aligned column">
                <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">Programação</h1>
            </div>
            <div class="eight wide mobile four wide tablet three wide computer center aligned column">
                <div class="row wow fadeInUp" data-wow-delay="0.5s">
                    <div class="ui vertical labeled icon menu">
                        {% include 'secompufscar2017/helpers/itens_menu_programacao.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'secompufscar2017/helpers/patrocinadores.html' %}

{% endblock body_content %}