secompufscar2015/urls.py
# coding: utf-8

from django.conf.urls import url
from secompufscar2018 import views

app_name = 'secompufscar2015'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # url(r'^apresentacao/$', views.apresentacao, name='apresentacao'),
    # url(r'^programacao/$', views.programacao, name='programacao'),
    # url(r'^cronograma/$', views.cronograma, name='cronograma'),
    # url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'),
    # url(r'^equipe/$', views.equipe, name='equipe'),
    # url(r'^contato/$', views.contato, name='contato'),
]

secompufscar2017/urls.py
# coding: utf-8

from django.conf.urls import include, url
from secompufscar2017 import views

app_name = 'secompufscar2017'
urlpatterns = [
    url(r'^area-do-participante/', include('secompufscar2017.urls_area_do_participante')),
    url(r'^area-administrativa/', include('secompufscar2017.urls_area_administrativa')),
    url(r'^api/', include('secompufscar2017.urls_apis')),
]

secompufscar_django/urls.py
from django.conf import settings
from django.conf.urls import include , handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

app_name = "secompufscar_django"


urlpatterns = [
    path('robots.txt', include('robots.urls')),
    path('admin/', admin.site.urls),
    path('2018/', include('secompufscar2018.urls', namespace='secompufscar2018')),
    path('2018/', include('secompufscar2017.urls', namespace='secompufscar2017')),
    path('2016/', include('secompufscar2016.urls', namespace='secompufscar2016')),
    path('2015/', include('secompufscar2015.urls', namespace='secompufscar2015')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', include('secompufscar2019.urls', namespace='root')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#handler404 = 'secompufscar2018.views.erro_404'
handler500 = 'secompufscar2018.views.erro_500'

secompufscar2017/models.py
from django.db import models


class CaraterProjeto(models.Model):
    carater = models.CharField(verbose_name="Caráter de projeto", max_length=15, unique=True)

    def __str__(self):
        return str(self.carater)


class Projeto(models.Model):
    # Atributos da tabela projeto
    nome = models.CharField(verbose_name="Nome do projeto", max_length=100)
    areas = models.CharField(verbose_name="Áreas abordadas", max_length=200)
    carater = models.ManyToManyField(CaraterProjeto, verbose_name='Carater do projeto')
    conteudo = models.TextField(verbose_name="Conteúdo abordado")
    descricao = models.TextField(verbose_name="Descrição do projeto")
    link_video = models.CharField(verbose_name="Link para vídeo", max_length=100, null=True, blank=True)
    relacao_computacao = models.TextField(verbose_name="Relação com a computação")
    material_utilizado = models.TextField(verbose_name="Material utilizado", blank=True)
    objetivo = models.TextField(verbose_name="Objetivo do projeto", max_length=2000)
    resultados = models.TextField(verbose_name="Resultados já alcançados")
    # Responsavel pelo projeto: os seguintes campos estão inclusos na tabela projeto
    # e não integrante pois são relativos ao único responsável pelo projeto.
    responsavel = models.ForeignKey('IntegranteProjeto', on_delete=models.CASCADE, null=True)
    facebook_responsavel = models.CharField(verbose_name="Facebook do responsável", max_length=100, null=True,
                                            blank=True)
    email_responsavel = models.EmailField(verbose_name="Email do responsável")
    telefone_responsavel = models.CharField(verbose_name="Telefone do responsavel", max_length=15)

    aprovado = models.NullBooleanField(verbose_name="Status de aprovação", null=True)

    def __str__(self):
        return 'Projeto: ' + str(self.nome)

    class Meta:
        verbose_name = 'projeto'
        verbose_name_plural = 'projetos'


class IntegranteProjeto(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=100)
    projeto_participante = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nome) + '[projeto: ' + self.projeto_participante.nome + ']'

    class Meta:
        verbose_name = 'integrante'
        verbose_name_plural = 'integrantes'

secompufscar2017/forms.py
from django import forms
from django.core.exceptions import ValidationError

from secompufscar2017.utilities import *
from secompufscar2017.models import CaraterProjeto
from secompufscar_bd.models import Curso, Instituicao


class FormularioDeContato(forms.Form):
    nome = forms.CharField(
        label='Seu nome',
        widget=forms.TextInput(attrs={'placeholder': 'Seu nome'}),
        error_messages={
            'required': 'Digite seu nome.'
        },
        help_text='Digite seu nome.'
    )
    email = forms.EmailField(
        label='Seu e-mail',
        widget=forms.EmailInput(attrs={'placeholder': 'Seu e-mail'}),
        error_messages={
            'required': 'Digite seu e-mail.',
            'invalid': 'Digite um e-mail válido.'
        },
        help_text='Digite seu e-mail.'
    )
    mensagem = forms.CharField(
        label='Sua mensagem',
        widget=forms.Textarea(attrs={'placeholder': 'Sua mensagem', 'rows': '5'}),
        error_messages={
            'required': 'Digite sua mensagem.'
        },
        help_text='Digite sua mensagem.'
    )


def instituicoes():
    return [('', 'Instituição')] + \
           [(instituicao.id, instituicao.nome) for instituicao in Instituicao.objects.all().order_by('nome')] + \
           [('0', 'Outra')]


def cursos():
    return [('', 'Curso')] + [(curso.id, curso.nome) for curso in Curso.objects.all().order_by('nome')] +\
           [('0', 'Outro')]


def ano_ingresso():
    return [(i, i) for i in range(2018, 2001, -1)]


class FormularioDeCadastro(forms.Form):
    email = forms.EmailField(
        label='E-mail',
        widget=forms.EmailInput(attrs={'placeholder': 'E-mail'}),
        error_messages={
            'required': 'Digite seu e-mail.',
            'invalid': 'Digite um e-mail válido.'
        },
        help_text='Digite seu e-mail.'
    )
    confirmacao_email = forms.EmailField(
        label='Confirmação do e-mail',
        widget=forms.EmailInput(attrs={'placeholder': 'Confirmação do e-mail'}),
        error_messages={
            'required': 'Digite novamente o seu e-mail.',
            'invalid': 'Digite um e-mail válido'
        },
        help_text='Digite novamente o seu e-mail.'
    )
    senha = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(attrs={'placeholder': 'Senha'}),
        error_messages={
            'required': 'Digite uma senha.'
        },
        help_text='Digite sua senha.'
    )
    confirmacao_senha = forms.CharField(
        label='Confirmação da senha',
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirmação da senha'}),
        error_messages={
            'required': 'Digite novamente a sua senha.'
        },
        help_text='Digite novamente a sua senha.'
    )
    nome = forms.CharField(
        label='Nome',
        widget=forms.TextInput(attrs={'placeholder': 'Nome'}),
        error_messages={
            'required': 'Digite seu nome.'
        },
        help_text='Digite seu nome.'
    )
    sobrenome = forms.CharField(
        label='Sobrenome completo',
        widget=forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
        error_messages={
            'required': 'Digite seu sobrenome.'
        },
        help_text='Digite seu sobrenome.'
    )
    instituicao = forms.MultipleChoiceField(
        label='Instituição',
        widget=forms.SelectMultiple(attrs={'placeholder': 'Curso'}),
        choices=instituicoes,
        required=False,
        error_messages={
            'invalid_choice': 'Opção escolhida inválida.'
        },
        help_text='Digite a instituição que estuda, se aplicável.'
    )
    outra_instituicao = forms.CharField(
        label='Outra instituição',
        widget=forms.TextInput(attrs={'placeholder': 'Qual?'}),
        required=False,
        help_text='Digite a instituição caso esta não esteja na lista.'
    )
    curso = forms.MultipleChoiceField(
        label='Curso',
        widget=forms.SelectMultiple(attrs={'placeholder': 'Curso'}),
        choices=cursos,
        required=False,
        error_messages={
            'invalid_choice': 'Opção escolhida inválida.'
        },
        help_text='Digite o curso que está cursando, se aplicável.'
    )
    outro_curso = forms.CharField(
        label='Outro curso',
        widget=forms.TextInput(attrs={'placeholder': 'Qual?'}),
        required=False,
        help_text='Digite o curso caso este não esteja na lista.'
    )
    ano_ingresso = forms.ChoiceField(
        label='Ano de ingresso',
        choices=ano_ingresso(),
        required=False,
        error_messages={
            'invalid_choice': 'Opção escolhida inválida.'
        },
        help_text='Digite o ano de ingresso no seu curso.'
    )


def _get_pacotes():
    return [(pacote.id, pacote.nome) for pacote in
            get_evento_atual().pacotes.filter(pacote_disponivel=True).order_by('ordem_site')]


def _get_camisetas_disponiveis(camisetas):
    camisetas_disponiveis = []
    for camiseta in camisetas:
        if camiseta.quantidade_restante > 0:
            camisetas_disponiveis.append(camiseta)
    return camisetas_disponiveis


def _get_camisetas():
    camisetas_disponiveis = _get_camisetas_disponiveis(get_evento_atual().camisetas.all().order_by('tamanho'))
    return [(camiseta.id, camiseta.tamanho) for camiseta in camisetas_disponiveis]


class FormularioDeInscricao(forms.Form):
    aceite_compartilhamento_email = forms.BooleanField(
        initial=True,
        label='Aceito receber e-mails de parceiros da IX SECOMP UFSCar.',
        widget=forms.CheckboxInput(),
        required=False,
        help_text='Nesta opção você autoriza ou não o compartilhamento do seu e-mail com os nossos patrocinadores.',
    )
    aceite_termos_inscricao = forms.BooleanField(
        initial=False,
        label='Aceito os termos de inscrição da IX SECOMP UFSCar.',
        widget=forms.CheckboxInput(),
        help_text='Para realizar a sua inscrição, você deve estar de acordo com os termos da IX SECOMP UFSCar.',
    )


class FormularioCamiseta(forms.Form):
    camiseta = forms.ChoiceField(
        label='Camiseta',
        widget=forms.RadioSelect,
        error_messages={
            'invalid_choice': 'A camiseta selecionada é inválida ou não está mais disponível.',
            'required': 'Você precisa selecionar uma camiseta.'
        },
        choices=_get_camisetas
    )


def _validar_cupom(cupom):
    cupons_validos = [cupom.codigo for cupom in get_evento_atual().cupons.filter(usado=False)]
    if cupom not in cupons_validos:
        raise ValidationError(u'Cupom de desconto inválido.')


class FormularioAplicarCupom(forms.Form):
    cupom = forms.CharField(
        label='Cupom',
        widget=forms.TextInput(attrs={'placeholder': 'Cupom de desconto'}),
        error_messages={
            'invalid_choice': 'Cupom inválido ou já utilizado.',
            'required': 'Você precisa inserir um cupom.'
        },
        validators=[_validar_cupom]
    )


def _validar_tipo_arquivo(arquivo):
    nome_arquivo = arquivo.name
    if nome_arquivo.endswith('.pdf') or nome_arquivo.endswith('.jpg') or nome_arquivo.endswith('.JPG') or \
            nome_arquivo.endswith('.jpeg') or nome_arquivo.endswith('.JPEG') or \
            nome_arquivo.endswith('.png') or nome_arquivo.endswith('.PNG'):
        return
    else:
        raise ValidationError(u'Tipo de arquivo não aceito.')


class FormularioEnvioComprovantePagamento(forms.Form):
    comprovante = forms.FileField(
        label='Comprovante',
        error_messages={
            'required': 'Você deve selecionar um arquivo para enviar.'
        },
        validators=[_validar_tipo_arquivo]
    )


def choices_carater_projeto():
    choices = [(carater.id, carater.carater) for carater in CaraterProjeto.objects.all().order_by('carater')]
    choices.append(('', 'Selecione uma ou mais opções'))
    return choices


class FormularioDeCadastroDeProjetos(forms.Form):
    nome_projeto = forms.CharField(
        label='Nome do projeto',
        widget=forms.TextInput(attrs={'placeholder': 'Nome do Projeto'}),
        error_messages={
            'required': 'Digite o nome do seu projeto.'
        },
        help_text='Digite o nome do seu projeto.'
    )
    carater_projeto = forms.MultipleChoiceField(
        label='Caráter do Projeto',
        widget=forms.SelectMultiple(attrs={'multiple': '', 'class': "ui dropdown"}),
        choices=choices_carater_projeto(),
        error_messages={
            'invalid_choice': 'Opção escolhida inválida.'
        },
        help_text='Selecione pelo menos uma opção que caracterize o projeto.'
    )

    conteudo = forms.CharField(
        label='Conteúdo abordado',
        widget=forms.Textarea(attrs={'placeholder': 'Conteúdo abordado pelo projeto', 'rows': '5'}),
        error_messages={
            'required': 'Digite o conteúdo abordado pelo seu projeto.'
        },
        help_text='Informe o conteúdo abordado pelo seu projeto.'
    )

    descricao = forms.CharField(
        label='Descrição do projeto',
        widget=forms.Textarea(attrs={'placeholder': 'Descrição do projeto', 'rows': '5'}),
        error_messages={
            'required': 'Digite a descrição do seu projeto.'
        },
        help_text='Descreva o seu projeto.'
    )

    link_video = forms.CharField(
        label='Link de vídeo',
        widget=forms.TextInput(attrs={'placeholder': 'Link para o vídeo do projeto'}),
        required=False,
        help_text='Digite um link para algum vídeo sobre seu projeto.'
    )

    relacao_computacao = forms.CharField(
        label='Relação com a computação',
        widget=forms.Textarea(attrs={'placeholder': 'Relação com a computação', 'rows': '5'}),
        error_messages={
            'required': 'Digite a relação do seu projeto com a computação.'
        },
        help_text='Informe a relação do seu projeto com a computação.'
    )

    material_utilizado = forms.CharField(

secompufscar2017/templates/secompufscar2017/area_administrativa/auto_atualizacao_quantidades_camisetas.html
<script type="text/javascript">
    function atualizarCamisetas() {
        {% for camiseta in evento.camisetas.all %}
            atualizarDisponibilidadeCamiseta({{ camiseta.id }}, '{{ camiseta.tamanho }}');
        {% endfor %}
    }

    function atualizarDisponibilidadeCamiseta(idCamiseta, tamanhoCamiseta) {
        return $.ajax({
            url: '{% url 'secompufscar2017:api_camisetas' id_camiseta='123456789' %}'.replace('123456789', idCamiseta),
            dataType: 'json',
            success: function (data) {
                if (data.quantidade_restante <= 0) {
                    desabilitarCamiseta(idCamiseta, tamanhoCamiseta, data.quantidade_restante)
                } else {
                    habilitarCamiseta(idCamiseta, tamanhoCamiseta, data.quantidade_restante);
                }
            },
            cache: false
        });
    }

    function habilitarCamiseta(idCamiseta, tamanhoCamiseta, quantidadeRestante) {
        $('#id_field_camiseta_' + idCamiseta + '.field').removeClass('error').removeClass('disabled');
        $('label[for=id_camiseta_' + idCamiseta + ']').text(tamanhoCamiseta + ' (' + quantidadeRestante + ')');
    }

    function desabilitarCamiseta(idCamiseta, tamanhoCamiseta) {
        $('#id_field_camiseta_' + idCamiseta + '.field').addClass('error').addClass('disabled');
        $('label[for=id_camiseta_' + idCamiseta + ']').text(tamanhoCamiseta + ' (esgotada)');
    }
</script>

secompufscar2017/templates/secompufscar2017/area_administrativa/modal_alterar_camiseta.html
<div class="ui large modal" id="id_modal_alterar_camiseta">
    <i class="close icon"></i>
    <div class="icon header">
        <i class="child icon"></i>
        Alterar tamanho da camiseta
    </div>
    <div class="content">
        <form class="ui form" id="id_formulario_camiseta"
              method="post">
            {% csrf_token %}
            <div class="ui grid">
                <div class="ui sixteen wide column">
                    <div class="field">
                        <label for="id_dropdown_selecionar_inscricao_com_kit">
                            Inscrições que compraram camisetas:</label>
                        <div class="ui live search selection scrooling dropdown"
                             id="id_dropdown_selecionar_inscricao_com_kit">
                            <i class="dropdown icon"></i>
                            <input type="hidden" name="inscricao" id="id_inscricao_camiseta">
                            <div class="default text">Selecione a inscrição</div>
                        </div>
                    </div>
                </div>
                <div class="ui sixteen wide column">
                    <h3 class="ui header">
                        Selecione a nova camiseta:
                    </h3>
                    <div class="grouped fields">
                        {% for camiseta in camisetas %}
                            <div class="{% if camiseta.quantidade_restante <= 0 %}error disabled {% endif %}field"
                                 id="id_field_camiseta_{{ camiseta.id }}">
                                <div class="ui radio checkbox">
                                    <label for="id_camiseta_{{ camiseta.id }}"
                                           id="id_label_camiseta_{{ camiseta.id }}">
                                        {{ camiseta.tamanho }}
                                        {% if camiseta.quantidade_restante > 0 %}
                                            ({{ camiseta.quantidade_restante }})
                                        {% endif %}
                                        {% if camiseta.quantidade_restante <= 0 %}
                                            (esgotada){% endif %}</label>
                                    <input type="radio" name="camiseta"
                                           value="{{ camiseta.id }}"
                                           id="id_camiseta_{{ camiseta.id }}"
                                           tabindex="0"
                                           class="hidden">
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="ui icon success message" id="id_alterar_camiseta_mensagem_sucesso">
                        <i class="check icon"></i>
                        <div class="content">
                            <div class="header">
                                Operação realizada!
                            </div>
                            Tamanho da camiseta alterado com sucesso.
                        </div>
                    </div>
                    <div class="ui icon error message" id="id_alterar_camiseta_mensagem_erro">
                        <i class="remove icon"></i>
                        <div class="content">
                            <div class="header">
                                Erro :-(
                            </div>
                            <span id="id_alterar_camiseta_conteudo_mensagem_erro"></span>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui blue button" id="id_botao_salvar_camisetas">
            <i class="save icon"></i>
            Salvar alteração
        </button>
    </div>
</div>

{% include 'secompufscar2017/area_administrativa/auto_atualizacao_quantidades_camisetas.html' %}

<script type="text/javascript">

    $('.ui.checkbox').checkbox();

    $('#id_botao_alterar_camisetas').on('click', function () {
        resetModalDeAlteracaoDeCamisetas();
        $('#id_dropdown_selecionar_inscricao_com_kit').dropdown({
            apiSettings: {
                url: "{%  url 'secompufscar2017:api_get_participantes_com_camiseta' %}",
                cache: false
            },
            message: {
                noResults: 'Nenhuma camiseta comprada :('
            },
            localSearch: false,
            saveRemoteData: false
        });
        $('#id_modal_alterar_camiseta').modal('show');
    });

    function resetModalDeAlteracaoDeCamisetas() {
        var formulario = $('#id_formulario_camiseta');
        formulario[0].reset();
        formulario.removeClass('error').removeClass('success');
        $('#id_modal_alterar_camiseta').modal('refresh');
    }

    var botaoSalvarAlteracao = $('#id_botao_salvar_camisetas');

    botaoSalvarAlteracao.addClass('disabled');

    $('#id_dropdown_selecionar_inscricao_com_kit').dropdown({
        apiSettings: {
            url: "{%  url 'secompufscar2017:api_get_participantes_com_camiseta' %}",
            cache: false
        },
        message: {
            noResults: 'Nenhum kit comprado :('
        },
        saveRemoteData: false
    }).on('change', function () {
            $('#id_detalhes_inscricao').hide(150);
            $('#id_formulario_camiseta').removeClass('success').removeClass('error');
            var id_inscricao = $('#id_inscricao_camiseta').val();

            $.ajax({
                url: "{% url 'secompufscar2017:api_get_detalhes_inscricao_all' id_inscricao='123456789' %}".replace('123456789', id_inscricao),
                data: function (data) {
                    return data.responseJSON;
                },
                success: function (data) {
                    atualizarCamisetas();
                    var camiseta = 'input#id_camiseta_' + data.camiseta_id.toString();
                    $(camiseta).prop('checked', true);
                    botaoSalvarAlteracao.removeClass('disabled');
                }
            });
    }).on('click', function () {
        $('#id_formulario_camiseta').removeClass('error').removeClass('success');
        $('#id_modal_alterar_camiseta').modal('refresh');
    });

    botaoSalvarAlteracao.on('click', function () {
        botaoSalvarAlteracao.addClass('loading');

        var formulario = $('#id_formulario_camiseta');
        formulario.removeClass('error').removeClass('success');
        $('#id_modal_alterar_camiseta').modal('refresh');

        $.post("{% url 'secompufscar2017:atualizar_tamanho_camisetas' %}", formulario.serialize())
            .done(function () {
                botaoSalvarAlteracao.removeClass('loading');
                formulario.removeClass('error').addClass('success');
                atualizarCamisetas();
                $('#id_modal_alterar_camiseta').modal('refresh');
            }).fail(function (data) {
                botaoSalvarAlteracao.removeClass('loading');
                formulario.removeClass('success').addClass('error');
                $('#id_alterar_camiseta_conteudo_mensagem_erro').text(data.responseJSON.mensagem);
                botaoAprovarComprovante.removeClass('disabled');
                $('#id_modal_alterar_camiseta').modal('refresh');
        });
    });

</script>

secompufscar2017/templates/secompufscar2017/area_administrativa/modal_enviar_email.html
<div class="ui large modal" id="id_modal_enviar_email">
    <i class="close icon"></i>
    <div class="header">
        Enviar email para todos os inscritos
    </div>
    <div class="scrooling content">
        <div class="description">
            <form class="ui form" id="id_formulario_enviar_email">
                {% csrf_token %}

                <div class="row">
                    <div class="field">
                        <label for="id_assunto">{{ form_enviar_email.assunto.label_tag }}</label>
                        {{ form_enviar_email.assunto }}
                    </div>

                </div>

                <div class="row">
                    <div class="field">
                        <label for="id_titulo">{{ form_enviar_email.titulo.label_tag }}</label>
                        {{ form_enviar_email.titulo }}
                    </div>

                </div>

                <div class="row">
                    <div class="field">
                        <label for="id_conteudo">{{ form_enviar_email.conteudo.label_tag }}</label>
                        {{ form_enviar_email.conteudo }}
                    </div>
                </div>

                <div class="ui success message">
                    <span><b>Emails enviados com sucesso!</b></span><br>

                    <span id="detalhes_sucesso_enviar_email"></span>
                </div>
                <div class="ui error message">
                    <span id="detalhes_erro_enviar_email"></span>
                </div>
            </form>
        </div>
    </div>
    <div class="actions">

        <button class="ui blue left floated button" id="id_botao_realizar_teste">
            <i class="mail forward icon"></i>
            Realizar teste
        </button>

        <button class="ui green button" id="id_botao_enviar_email">
            <i class="send icon"></i>
            Enviar email
        </button>
    </div>
</div>

<script type="text/javascript">


    $('#id_botao_abrir_modal_enviar_email').on('click', function () {
        $('#id_modal_enviar_email').modal('show');
    });

    var botaoEnviarEmail = $('#id_botao_enviar_email');
    var botaoRealizarTeste = $('#id_botao_realizar_teste');
    var formulario = $('#id_formulario_enviar_email');

    formulario.removeClass('success').removeClass('error');

    botaoRealizarTeste.on('click', function () {
        botaoRealizarTeste.addClass('loading');

        formulario.removeClass('success').removeClass('error');

        $.post("{% url 'secompufscar2017:realizar_teste_email' %}", formulario.serialize())
            .done(function (data) {
                botaoRealizarTeste.removeClass('loading');
                formulario.removeClass('error');
                formulario.addClass('success');
                $('#detalhes_sucesso_enviar_email').text(JSON.parse(data.responseText).mensagem);
            }).fail(function (data) {
            botaoRealizarTeste.removeClass('loading');
            formulario.removeClass('success');
            formulario.addClass('error');
            $('#detalhes_erro_enviar_email').text(JSON.parse(data.responseText).mensagem);
        });
    });

    botaoEnviarEmail.on('click', function () {
        botaoEnviarEmail.addClass('loading');

        formulario.removeClass('success').removeClass('error');

        $.post("{% url 'secompufscar2017:enviar_email_generico' %}", formulario.serialize())
            .done(function (data) {
                botaoEnviarEmail.removeClass('loading');
                formulario.removeClass('error');
                formulario.addClass('success');
                $('#detalhes_sucesso_enviar_email').text(JSON.parse(data.responseText).mensagem);

            }).fail(function (data) {
            botaoEnviarEmail.removeClass('loading');
            formulario.removeClass('success');
            formulario.addClass('error');
            $('#detalhes_erro_enviar_email').text(JSON.parse(data.responseText).mensagem);
        });
    });
</script>

secompufscar2017/templates/secompufscar2017/area_administrativa/modal_enviar_notificacao.html
<div class="ui large modal" id="id_modal_enviar_notificacao">
    <i class="close icon"></i>
    <div class="icon header">
        <i class="android icon"></i>
        Enviar notificações para o aplicativo
    </div>
    <div class="content">
        <div class="description">
            <form class="ui form" id="id_formulario_enviar_notificacao" novalidate>
            {% csrf_token %}
                <div class="row">
                {{ form_enviar_notificacao.mensagem }}
                </div>
                 <div class="row" align="right">
                    <p><span id="caracteres">135</span> caracteres restantes</p>
                </div>
                <div class="ui success message">
                    <b>Deu bom! o/</b><br>
                    A notificação foi enviada para o Firebase e Twitter com sucesso!
                </div>
                <div class="ui error message">
                    <span><b>Ops, deu ruim :-(</b></span><br>
                    <span id="detalhes_erro_enviar_notificacao"></span>
                </div>
            </form>
        </div>
    </div>
    <div class="actions">
        <button class="ui blue button" id="id_botao_enviar_notificacao">
            <i class="send icon"></i>
            Enviar notificação
        </button>
    </div>
</div>

<script type="text/javascript">

    $('#id_botao_enviar_notificacoes').on('click', function () {
        $('#id_modal_enviar_notificacao').modal('show');
        resetarModalEnviarNotificacoes();
    });

    function resetarModalEnviarNotificacoes() {
        $('#id_mensagem').val("");
        $("#caracteres").text("135");
        $('#id_formulario_enviar_notificacao').removeClass('error').removeClass('success');
        $('#id_modal_enviar_notificacao').modal('refresh');
        botaoEnviarNotificacao.addClass('disabled');
    }

    var botaoEnviarNotificacao = $('#id_botao_enviar_notificacao');

    botaoEnviarNotificacao.on('click', function () {
        botaoEnviarNotificacao.addClass('loading');

        var formulario = $('#id_formulario_enviar_notificacao');
        formulario.removeClass('success').removeClass('error');

        $.post("{% url 'secompufscar2017:enviar_notificacao' %}", formulario.serialize())
            .done(function () {
                botaoEnviarNotificacao.removeClass('loading');
                formulario.addClass('success');
                $('#id_modal_enviar_notificacao').modal('refresh');
            }).fail(function(data) {
                botaoEnviarNotificacao.removeClass('loading');
                formulario.addClass('error');
                $('#detalhes_erro_enviar_notificacao').text(data.mensagem);
                $('#id_modal_enviar_notificacao').modal('refresh');
        });
    });

    $('#id_mensagem').on('input', function() {
        var limite = 135;
        var caracteresDigitados = $(this).val().length;
        var caracteresRestantes = limite - caracteresDigitados;

        $("#caracteres").text(caracteresRestantes);

        if (caracteresDigitados > 0) {
            botaoEnviarNotificacao.removeClass('disabled');
        }
    });

</script>