secompufscar2015/urls.py
# coding: utf-8

from django.conf.urls import url
from secompufscar2018 import views

app_name = 'secompufscar2015'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # url(r'^apresentacao/$', views.apresentacao, name='apresentacao'),
    # url(r'^programacao/$', views.programacao, name='programacao'),
    # url(r'^cronograma/$', views.cronograma, name='cronograma'),
    # url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'),
    # url(r'^equipe/$', views.equipe, name='equipe'),
    # url(r'^contato/$', views.contato, name='contato'),
]

secompufscar2019/urls.py
import locale

from django.conf.urls import include
from django.urls import path

from secompufscar2019 import views

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
app_name = 'secompufscar2019'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq', views.faq, name='faq'),
    path('patrocinio', views.patrocinio, name='patrocinio'),
    path('equipe', views.equipe, name='equipe'),
    path('a-secomp/', views.a_secomp, name='asecomp'),
    path('a-secomp/apresentacao/', views.apresentacao, name='apresentacao'),
    path('a-secomp/sociocultural/', views.sociocultural, name='sociocultural'),
    path('area-conteudo/',include('secompufscar2019.urls_area_conteudo')),
    path('recaptcha/', views.erro_recaptcha, name='recaptcha'),
    path('contato/enviar-email/', views.enviar_email_contato, name='enviar_email_contato'),
    path('404/', views.erro_404, name='404'),
    path('500/', views.erro_500, name='400')
]

secompufscar_django/urls.py
from django.conf import settings
from django.conf.urls import include , handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

app_name = "secompufscar_django"


urlpatterns = [
    path('robots.txt', include('robots.urls')),
    path('admin/', admin.site.urls),
    path('2018/', include('secompufscar2018.urls', namespace='secompufscar2018')),
    path('2018/', include('secompufscar2017.urls', namespace='secompufscar2017')),
    path('2016/', include('secompufscar2016.urls', namespace='secompufscar2016')),
    path('2015/', include('secompufscar2015.urls', namespace='secompufscar2015')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', include('secompufscar2019.urls', namespace='root')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#handler404 = 'secompufscar2018.views.erro_404'
handler500 = 'secompufscar2018.views.erro_500'

secompufscar2019/models.py
import datetime
import os
from django.db import models

DIRETORIAS =(
    ('SC','Sociocultural'),
    ('DM','Design e Marketing'),
    ('TI','Tecnologia de Informação'),
    ('JF','Jurídico-Financeira'),
    ('PA','Patrocínio'),
    ('CO','Conteúdo')
)
CURSOS =(
    ('BCC','Bacharelado em Ciência da Computação'),
    ('ENC','Eng. de Computação'),
    ('PPG','Pós Graduação'),
)

class ProcessoSeletivo(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, blank=False, default="")
    email = models.EmailField(max_length=100, blank=False, default="",unique=True)
    tel = models.CharField(max_length=20, blank=False, unique=True, default="")
    aprovado = models.BooleanField(default=False)
    primeira_opcao = models.CharField(blank=False, choices=DIRETORIAS, max_length=2)
    segunda_opcao = models.CharField(blank=False, choices=DIRETORIAS, max_length=2 )
    curso = models.CharField(max_length=3,choices=CURSOS, blank=False)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)
    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Processo Seletivo')
        verbose_name_plural = (u'Processo Seletivo')

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

secompufscar2019/views.py
from django import template
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Min
from django.db.models.signals import post_save, post_delete, m2m_changed
from django.dispatch import receiver
from django.shortcuts import render
from django.utils import timezone
import requests
from secompufscar2017.forms import FormularioDeContato
from secompufscar2017.utilities import abreviar_sobrenome, criar_resposta_json_sucesso, criar_resposta_json_erro, get_email_pronto_para_envio, enviar_email
from secompufscar2017.views import is_sistema_em_producao, get_google_analytics_key, AGORA, _enviar_email_de_contato
from secompufscar2019.constants import *
from secompufscar2019.utilities import get_evento_atual
from secompufscar2019.forms import ProcessoSeletivoForm
from secompufscar2018.models import ConteudoMiniCurso, ConteudoPalestra, ConteudoMesaRedonda, MadDog
from secompufscar_bd.models import Diretoria, TipoAtividade
from secompufscar_django import settings

register = template.Library()


@register.filter(name='has_group')
def has_group(user, group_name):
	group = Group.objects.get(name=group_name)
	return group in user.groups.all()


evento = get_evento_atual()


def _get_patrocinadores_por_cota(nome_cota):
	return evento.patrocinadores.filter(ativo_site=True, cota__nome=nome_cota).order_by('ordem_site')


def get_todos_ministrantes():
	minicurso = ConteudoMiniCurso.objects.all()
	palestrantes = ConteudoPalestra.objects.all()
	mesaredonda = ConteudoMesaRedonda.objects.all()
	maddog = MadDog.objects.all()

	ministrantes = []
	for m in minicurso:
		if m.nome not in [pessoas['nome'] for pessoas in ministrantes]:
			ministrantes.append(
				{'id': m.id,
				 'nome': m.nome,
				 'tipo': TIPO_MINICURSO,
				 'foto': str(m.foto)}
			)

	for m in mesaredonda:
		if m.nome not in [pessoas['nome'] for pessoas in ministrantes]:
			ministrantes.append(
				{'id': m.id,
				 'nome': m.nome,
				 'tipo': TIPO_MESA_REDONDA,
				 'foto': str(m.foto)}
			)

	for m in palestrantes:
		if m.nome not in [pessoas['nome'] for pessoas in ministrantes]:
			ministrantes.append(
				{'id': m.id,
				 'nome': m.nome,
				 'tipo': TIPO_PALESTRA,
				 'foto': str(m.foto)}
			)

	for m in maddog:
		ministrantes.append(
			{
				'id': m.id,
				'nome': m.nome,
				'tipo': TIPO_MADDOG,
				'foto': str(m.foto)
			}
		)

	return ministrantes

def _ajustar_tamanho_de_nome_para_pagina_equipe(membros):
	for membro in membros:
		sobrenome_completo = membro.participante.usuario.last_name
		membro.participante.usuario.last_name = abreviar_sobrenome(sobrenome_completo=sobrenome_completo, min_len=20)
	return membros


def _get_data_hora_inicio_evento():
	return evento.data_hora_inicio_evento


def _get_diretorias():
	return [{'nome': diretoria.nome,
			 'membros': _ajustar_tamanho_de_nome_para_pagina_equipe(evento.membros_equipe.filter(
				 diretoria=diretoria).order_by('-cargo__nome', 'participante__usuario__first_name',
											   'participante__usuario__last_name'))}
			for diretoria in Diretoria.objects.all()]


def _get_menus_site_ativos():
	return [menu.nome for menu in get_evento_atual().menus_site_ativos.filter(ativo=True)]


def _get_perguntas_frequentes():
	return evento.perguntas_frequentes.order_by('prioridade')

def _get_tipo_atividade(nome_tipo_atividade):
	try:
		return TipoAtividade.objects.get(nome=nome_tipo_atividade)
	except ObjectDoesNotExist:
		return None


def _get_atividades_por_tipo(nome_tipo_atividade):
	return evento.atividades.filter(ativa=True, tipo=_get_tipo_atividade(nome_tipo_atividade=nome_tipo_atividade)). \
		annotate(primeira_data=Min('horarios__data_hora_inicio')).order_by('primeira_data', 'titulo')


def TIPO_ATIVIDADE_(args):
	pass


def _get_dicionario_contexto():
	return {
		'producao': is_sistema_em_producao(),
		'google_analytics_key': get_google_analytics_key(),
		'patrocinadores': {
			'diamante': _get_patrocinadores_por_cota(nome_cota='Diamante'),
			'ouro': _get_patrocinadores_por_cota(nome_cota='Ouro'),
			'prata': _get_patrocinadores_por_cota(nome_cota='Prata'),
			'apoio': _get_patrocinadores_por_cota(nome_cota='Apoio'),
		},
		PALESTRAS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PALESTRA),
		PALESTRAS_EMPRESARIAIS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PALESTRA_EMPRESARIAL),
		MINICURSOS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_MINICURSO),
		WORKSHOPS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_WORKSHOP),
		MESAS_REDONDAS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_MESA_REDONDA),
		PROCESSOS_SELETIVOS: _get_atividades_por_tipo(nome_tipo_atividade=TIPO_ATIVIDADE_PROCESSO_SELETIVO),
		'diretorias': _get_diretorias(),
		'perguntas_frequentes': _get_perguntas_frequentes(),
		'menus_ativos': _get_menus_site_ativos(),
		'data_hora_inicio_evento': _get_data_hora_inicio_evento(),
		'evento': get_evento_atual(),
		'permissoes': {},
		'ministrantes': get_todos_ministrantes(),
		'form':None
	}


dicionario_contexto = _get_dicionario_contexto()


def atualizar_dicionario_permissoes():
	dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA'] = []
	for permissao in get_evento_atual().permissoes.all():
		dicionario_contexto['permissoes'][permissao.nome] = []
		for participante in permissao.usuarios_permitidos.all():
			dicionario_contexto['permissoes'][permissao.nome].append(participante.usuario)
			if participante.usuario not in dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA']:
				dicionario_contexto['permissoes']['AREA_ADMINISTRATIVA'].append(participante.usuario)


def _atualizar_dicionario_contexto():
	dicionario_contexto.update(_get_dicionario_contexto())
	atualizar_dicionario_permissoes()


@receiver(post_save, sender=Evento)
@receiver(post_delete, sender=Evento)
def _atualizar_evento_dicionario_contexto(sender, **kwargs):
	_atualizar_dicionario_contexto()

m2m_changed.connect(_atualizar_evento_dicionario_contexto, sender=Evento.menus_site_ativos.through)
m2m_changed.connect(_atualizar_evento_dicionario_contexto, sender=Evento.tipos_atividades.through)
m2m_changed.connect(_atualizar_evento_dicionario_contexto, sender=Evento.membros_equipe.through)


def enviar_email_contato(request):
	if request.method == 'POST':
		formulario_contato = FormularioDeContato(request.POST)
		if formulario_contato.is_valid():
			nome = formulario_contato.cleaned_data['nome']
			email = formulario_contato.cleaned_data['email']
			mensagem = formulario_contato.cleaned_data['mensagem']
			recaptcha_response = request.POST.get('g-recaptcha-response')
			data = {
				'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
				'response': recaptcha_response
			}
			r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
			result = r.json()
			if result['success']:
				if _enviar_email_de_contato(nome=nome, email=email, mensagem=mensagem):
					return criar_resposta_json_sucesso('E-mail enviado com sucesso.')
				else:
					return criar_resposta_json_erro(mensagem='Erro no serviço de envio de e-mail.', status_code=503)
			else:
				return criar_resposta_json_erro(mensagem='ReCaptcha inválido.', status_code=503)
		else:
			return criar_resposta_json_erro(mensagem='Parâmetros inválidos.', status_code=400)
	else:
		return criar_resposta_json_erro(mensagem='Métodos permitidos: [POST]', status_code=405)


def _enviar_email_de_caravanas(email, cidade, integrantes):
	contexto = {'nome': 'Um caboclo ai', 'email': email, 'mensagem': 'Cidade de partida: ' +  cidade + '\nLista de integrantes: ' + integrantes}
	assunto = 'Caravanas'
	destinatario = EMAIL_CONTATO_SECOMP if is_sistema_em_producao() else EMAIL_TI_SECOMP
	corpo_email = get_email_pronto_para_envio(assunto=assunto, remetente=email,
											  destinatario=destinatario, template=TEMPLATE_EMAIL_DE_CONTATO,
											  contexto=contexto, nome_remetente='Um caboclo ai')
	return enviar_email(corpo_email=corpo_email)


def enviar_email_caravana(request):
	if request.method == 'POST':
		form = request.POST
		email = form['email']
		cidade = form['cidade']
		integrantes = form['integrantes']
		recaptcha_response = request.POST.get('g-recaptcha-response')
		data = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
		}
		r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
		result = r.json()
		if result['success']:
			if _enviar_email_de_caravanas(email=email, cidade=cidade, integrantes=integrantes):
				return criar_resposta_json_sucesso('E-mail enviado com sucesso.')
			else:
				return criar_resposta_json_erro(mensagem='Erro no serviço de envio de e-mail.', status_code=503)
		else:
			return criar_resposta_json_erro(mensagem='ReCaptcha inválido.', status_code=503)
	else:
		return criar_resposta_json_erro(mensagem='Métodos permitidos: [POST]', status_code=405)


def index(request):
	dicionario_contexto[AGORA] = timezone.now()
	dicionario_contexto['quantidade_inscritos'] = get_evento_atual().inscricoes.count()
	return render(request=request, template_name=TEMPLATE_INDEX, context=dicionario_contexto)


def faq(request):
	dicionario_contexto['form'] = FormularioDeContato()
	return render(request=request, template_name=TEMPLATE_FAQ, context=dicionario_contexto)

def equipe(request):
	if request.user.is_authenticated:
		username = request.user.first_name
		dicionario_contexto['easter'] = username
	else:
		dicionario_contexto['easter'] = "Caroline"

	return render(request=request, template_name=TEMPLATE_EQUPE, context=dicionario_contexto)


def patrocinio(request):
	return render(request=request, template_name=TEMPLATE_PATROCINIO, context=dicionario_contexto)


def a_secomp(request):
	return render(request=request, template_name=TEMPLATE_SOBRE, context=dicionario_contexto)


def apresentacao(request):
	return render(request=request, template_name=TEMPLATE_APRESENTACAO, context=dicionario_contexto)


# TODO: Implementar a página história

secompufscar2019/templates/secompufscar2019/area_conteudo/maddog/form_maddog.html
{% extends 'secompufscar2019/helpers/base.html' %}
{% load staticfiles %}

{% block title %}SECOMP UFSCar - Special form for you{% endblock %}

{% block meta_description %}Contribua para a SECOMP IX com um conteúdo.{% endblock meta_description %}

{% block body_content %}
    <script src='https://www.google.com/recaptcha/api.js?hl=pt-BR'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>
    <div class="ui vertical stripe segment secao_fundo_cinza">
        <h1 class="ui centered header titulo_pagina wow fadeInUp" data-wow-delay="0.3s">
            MadDog
        </h1>
        <div class="ui container">
            <div class="ui stackable ordered fluid mobile mini steps wow fadeInUp" data-wow-delay="0.3s">
                <div class="active step" id="one">
                    <div class="content">
                        <div class="title">Personal</div>
                        <div class="description">

                        </div>
                    </div>
                </div>
                <div class="step" id="two">
                    <div class="content">
                        <div class="title">Lecture</div>
                        <div class="description">

                        </div>
                    </div>
                </div>
                <div class="step" id="three">
                    <div class="content">
                        <div class="title">Acommodation and transport</div>
                        <div class="description">

                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <form class="ui form" method="POST" name="cleiton" id="post-form" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="ui hidden divider mobile only"></div>
                    {% include 'secompufscar2019/area_conteudo/maddog/forms_parts/maddog_one.html' %}
                    {% include 'secompufscar2019/area_conteudo/maddog/forms_parts/maddog_two.html' %}
                    {% include 'secompufscar2019/area_conteudo/maddog/forms_parts/maddog_three.html' %}
                </form>
                <div class="ui icon success message" id="sucesso">
                        <i class="send icon"></i>
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">Hello Mr. Maddog. Your form was sent successfully!</div>
                            <p>We will contact you soon! :-)</p>
                            <p><a class="ui positive button" href="{% url 'secompufscar2019:index' %}">Back</a></p>
                        </div>
                    </div>

                    <div class="ui icon error message" id="erro">
                        <i class="frown icon"></i>
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">There was an error submitting your form!</div>
                            <div id="msgs"></div>
                            <p>If you think you should not be seeing this, please contact at <a
                                    href="mailto:ti@secompufscar.com.br">
                                ti@secompufscar.com.br</a> and report it
                            </p>
                        </div>
                    </div>
                    <div class="ui icon warning message" id="captcha_warning">
                        <i class="close icon"></i>
                        <div class="content">
                            <div class="header">Fill in the CAPTCHA</div>
                            <p> I know you are not a robot, Mr. Maddog! But unfortunately our server does not. :/
                            </p>
                        </div>
                    </div>
            </div>
        </div>
    </div>

    {% include 'secompufscar2019/helpers/patrocinadores.html' %}
    <script src="{% static 'secompufscar2019/js/formulario_maddog.js' %}"></script>
{% endblock body_content %}